### PR TITLE
Add search for token list, fixes #69

### LINKED ISSUE #69: Search for tokens
The token-list is already very long (and gets longer very fast - see https://github.com/MyEtherWallet/ethereum-lists/issues/191 ) - so we need a search function for tokens

### PR DESCRIPTION
**Pull request by friedger**
Search field has been added to select token activity.

screenshot_1509898257

### CODE REVIEW

**Comment by friedger** [comment]
Maybe move search field into action bar as suggested here 
https://github.com/walleth/walleth/pull/84#issuecomment-342039231

Search in the action bar feel more like one feature among other, not like being the main action. Not sure what you would like to have. However, the text field takes a lot of UI space.

**Comment by ligi** [comment]
Yes - I think I would like it in the ActionBar a bit more - can also rewrite it to be like this if you don't want to

**Comment by ligi** [comment]
Do you want to finish this - otherwise I would rework it so that it is in the ActionBar

**Comment by friedger** [comment]
Working on it now!

**Comment by friedger** [comment]
The search value is not persisted when rotating but that should be handled by Android. We could open a new issue for that.

**Comment by friedger** [comment]
@ligi Feel free to review again :-)

**Comment by ligi** [comment]
YAY - lgtm!

just a minor detail:

screenshot_1511534409

the color is off in night mode - gets correct once you enter one char:

screenshot_1511534417

But I think I will still merge it - and open a follow-up ticket for this

**Comment by ligi** [comment]
Found a fix for the color problem:

```
        <item name="colorControlHighlight">?android:textColorPrimary</item>
        <item name="android:textColorHint">?android:textColorPrimary</item>
        <item name="android:editTextColor">?android:textColorPrimary</item>
```

in styles.xml for wallethActionBarThemeOverlay

**Comment by ligi** [comment]
When playing around with it a bit more I found a blocker though. It doesn't play nice with swipe-to delete. This still uses the old unsorted list with the index of the sorted one.

**Comment by ligi** [comment]
Will still merge it - this fix is quite trivial and will do it as a follow-up commit. Did you get the invitation to the organisation? Only then I can assign the issue to you which is a limitation for issuETH currently ..

**Pull request merged**
