### PR TITLE
105/Change token

### LINKED ISSUE #105: Change token in create-tx activity

### PR DESCRIPTION
**Pull request by friedger**
This PR allows the user to change the current token while creating a transaction.

The current amount is changed according to the tokens decimals, i.e. the user switches between 1ETH -> 1WALL, not 1ETH -> 1000WALL (with ETH 18 decimals and WALL 15 decimals).

Fixes #105 

Depends on #161

### CODE REVIEW

**Comment by friedger** [comment]
Closed until #161 is merged.

**Comment by ligi** [comment]
161 is merged now - reopening. Also this is kind of needed now - as 161 is changing from token to eth when scanning an address - we need to fix that also - should only change the token when a value is in the erc-681 URL

**Comment by friedger** [comment]
LGTM

**Comment by ligi** [comment]
:+1:

**Pull request merged**
