### PR TITLE
2/add transfer of addresses

### PR DESCRIPTION
**Pull request by friedger**
This PR adds the possibility to export and import the address book.

It is only supported for devices with Android 19+

The UX for creating or opening the export location could be improved. Currently, a new file is created everytime.

### CODE REVIEW

**Comment by ligi** [comment]
Nice initiative! Perhaps we should add a container-format with some kind of versioning to be a bit future-proof.
{ "content":"addresses", "version":1, entries:[] }

**Comment by friedger** [comment]
I added the container and a test.

I had to remove the "takePersistableUriPermission" until I find a solution for my question:
https://stackoverflow.com/questions/49101100/how-to-return-a-uri-with-granted-permission-in-espressos-intenting

**Comment by ligi** [comment]
Sorry for the merge-delay - but I am currently having problems getting these PRs green on my CI

**Comment by ligi** [comment]
to bad this SO answer never got a reply so far :-(
The test failing for me is the importsTheExportCorrectly - interestingly works on my emulator - but fails on the connected real device

**Comment by ligi** [comment]
Closing as the tests where flaky and never green on my ci - feel free to reopen when the tests are not flaky anymore.

**Pull request closed without merging**
